import logging
import traceback

import flet as ft

from w3stringsx_lib.logging import init_logger, set_log_level, get_logger
from w3stringsx_ioc import di
from w3stringsx_svc import (
    Configuration,
    StringKeyDiscoveryService,
    W3StringsEncoderLocator, FromConfigW3stringsEncoderLocatorHandler, AppDirW3StringsEncoderLocatorHandler, PathEnvW3stringsEncoderLocatorHandler,
    W3StringsEncoder,
    W3StringsManagerService,
    ScratchFolderService
)
from w3stringsx_gui.services import (
    PageProvider,
    W3stringsxGuiConfiguration
)


def setup_services(page: ft.Page):
    page_provider = PageProvider()
    page_provider.acquire(page)

    config = W3stringsxGuiConfiguration(page_provider)
    config.initialize()

    init_logger(config.app_dir.get_required())
    set_log_level(logging.INFO)

    page.theme_mode = ft.ThemeMode(config.theme_mode.get_required())

    container = di.container_builder()\
        .singleton(PageProvider, page_provider)\
        .abstract_singleton(Configuration, W3stringsxGuiConfiguration, config)\
        .singleton(W3StringsEncoderLocator,
            W3StringsEncoderLocator()
            .with_handler(FromConfigW3stringsEncoderLocatorHandler(config))\
            .with_handler(AppDirW3StringsEncoderLocatorHandler(config))\
            .with_handler(PathEnvW3stringsEncoderLocatorHandler()))\
        .transitive(W3StringsEncoder)\
        .singleton_resource(ScratchFolderService)\
        .transitive(W3StringsManagerService)\
        .singleton(StringKeyDiscoveryService)\
        .build()
    
    di.push_container(container)

def main(page: ft.Page):
    setup_services(page)

    page.title = "w3stringsx GUI"
    page.window.width = 1400
    page.window.height = 1000
    page.scroll = ft.ScrollMode.ADAPTIVE

    # themes generated by perplexity.ai based on https://colorhunt.co/palette/d84040a31d1decdcbff8f2de
    page.theme = ft.Theme(
        color_scheme=ft.ColorScheme(
            primary="#D84040",               # Vibrant red primary
            on_primary="#FFFFFF",            # White text/icons on primary
            primary_container="#ECDCBF",    # Soft beige container
            on_primary_container="#3A1B00", # Dark brown text on container

            secondary="#A31D1D",             # Dark red secondary
            on_secondary="#FFFFFF",          # White text/icons on secondary
            secondary_container="#F8F2DE",  # Very light cream container
            on_secondary_container="#553D00",# Dark brown text on secondary container

            background="#F8F2DE",            # Very light cream background
            on_background="#3A1B00",         # Dark brown text on background

            surface="#FFFFFF",               # White surface for cards etc.
            on_surface="#3A1B00",            # Dark brown text on surface

            error="#B00020",
            on_error="#FFFFFF",
        )
    )
    page.dark_theme = ft.Theme(
        color_scheme=ft.ColorScheme(
            primary="#D84040",               # Same primary vibrancy
            on_primary="#FFFFFF",            # Light text/icons on primary
            primary_container="#6E2C2C",    # Darker shade for container
            on_primary_container="#FBE8E8", # Light text on container

            secondary="#A31D1D",             # Same secondary
            on_secondary="#FFFFFF",          # Light text icons
            secondary_container="#4F0A0A",  # Darker container
            on_secondary_container="#FBE8E8",# Light text

            background="#121212",             # Deep dark background
            on_background="#FFFFFF",          # Light text

            surface="#121212",                # Same as background
            on_surface="#FFFFFF",

            error="#CF6679",
            on_error="#000000",
        )
    )


    from w3stringsx_gui.components import LogsPanel

    page.overlay.append(LogsPanel(
        height=350,
        bottom=5,
        left=5,
        right=5,
    ))


    def page_on_error(ev: ft.ControlEvent):
        logger = get_logger()
        logger.error(ev.data)
        logger.error(traceback.format_exc())
    def page_on_app_lifecycle_state_change(ev: ft.AppLifecycleStateChangeEvent):
        # DETACH doesn't seem to get called on desktop
        if ev.state in (ft.AppLifecycleState.HIDE, ft.AppLifecycleState.DETACH):
            di.release_resources()
             
    page.on_error = page_on_error
    page.on_app_lifecycle_state_change = page_on_app_lifecycle_state_change


    from w3stringsx_gui.routing import Routes, Router
    from w3stringsx_gui.views.home_view import HomeView
    from w3stringsx_gui.views.settings_view import SettingsView
    from w3stringsx_gui.views.encode_strings_view import EncodeStringsView
    from w3stringsx_gui.views.decode_strings_view import DecodeStringsView
    from w3stringsx_gui.views.search_for_string_keys_view import SearchForStringKeysView

    router = Router(page).with_routes({
        Routes.HOME: HomeView,
        Routes.SETTINGS: SettingsView,
        Routes.ENCODE_STRINGS: EncodeStringsView,
        Routes.DECODE_STRINGS: DecodeStringsView,
        Routes.SEARCH_FOR_STRING_KEYS: SearchForStringKeysView,
    })

    router.goto(Routes.HOME)


ft.app(main)
