import logging
import traceback
from typing import Type

import flet as ft

from w3stringsx_lib.logging import init_logger, set_log_level, get_logger
from w3stringsx_ioc import di
from w3stringsx_svc import (
    Configuration,
    StringKeyDiscoveryService,
    W3StringsEncoderLocator, FromConfigW3stringsEncoderLocatorHandler, AppDirW3StringsEncoderLocatorHandler, PathEnvW3stringsEncoderLocatorHandler,
    W3StringsEncoder,
    W3StringsManagerService
)
from w3stringsx_gui.views.view_base import ViewBase
from w3stringsx_gui.routing import Routes, Router, ViewRoute
from w3stringsx_gui.services import (
    PageProvider,
    W3stringsxGuiConfiguration
)
from w3stringsx_gui.views import (
    HomeView, 
    SettingsView,
    EncodeStringsView, 
    DecodeStringsView, 
    SearchForStringKeysView
)


ROUTE_MAP: dict[str, Type[ViewBase]] = {
    Routes.HOME: HomeView,
    Routes.SETTINGS: SettingsView,
    Routes.ENCODE_STRINGS: EncodeStringsView,
    Routes.DECODE_STRINGS: DecodeStringsView,
    Routes.SEARCH_FOR_STRING_KEYS: SearchForStringKeysView,
}

def setup_services(page: ft.Page):
    page_provider = PageProvider()
    config = W3stringsxGuiConfiguration(page_provider)

    # FIXME either encoder should be transitive or its service should be reloaded
    container = di.container_builder()\
        .singleton(PageProvider, page_provider)\
        .abstract_singleton(Configuration, W3stringsxGuiConfiguration, config)\
        .singleton(W3StringsEncoder)\
        .singleton(StringKeyDiscoveryService)\
        .transitive_factory(W3StringsEncoderLocator, lambda resolver:
            W3StringsEncoderLocator(config)
            .with_handler(FromConfigW3stringsEncoderLocatorHandler(resolver.resolve(Configuration)))
            .with_handler(AppDirW3StringsEncoderLocatorHandler(resolver.resolve(Configuration)))
            .with_handler(PathEnvW3stringsEncoderLocatorHandler()))\
        .singleton(W3StringsManagerService)\
        .build()
    
    di.push_container(container)

    page_provider.acquire(page)
    init_logger(config.app_dir.get_required())
    set_log_level(logging.INFO)

    theme_mode_str = config.theme_mode.get()
    # memorize default theme
    if theme_mode_str is None:
        theme_mode_str = ft.ThemeMode.SYSTEM.value
        config.theme_mode = theme_mode_str
    if theme_mode_str in [member.value for member in list(ft.ThemeMode)]:
        theme_mode = ft.ThemeMode(theme_mode_str)
    else:
        theme_mode = ft.ThemeMode.SYSTEM
    page.theme_mode = theme_mode

def main(page: ft.Page):
    setup_services(page)

    page.title = "w3stringsx GUI"
    page.window.width = 1400
    page.window.height = 900
    page.scroll = ft.ScrollMode.ADAPTIVE

    def on_error(ev: ft.ControlEvent):
        logger = get_logger()
        logger.error(ev.data)
        logger.error(traceback.format_exc())
    page.on_error = on_error

    # themes generated by perplexity.ai based on https://colorhunt.co/palette/d84040a31d1decdcbff8f2de
    page.theme = ft.Theme(
        color_scheme=ft.ColorScheme(
            primary="#D84040",               # Vibrant red primary
            on_primary="#FFFFFF",            # White text/icons on primary
            primary_container="#ECDCBF",    # Soft beige container
            on_primary_container="#3A1B00", # Dark brown text on container

            secondary="#A31D1D",             # Dark red secondary
            on_secondary="#FFFFFF",          # White text/icons on secondary
            secondary_container="#F8F2DE",  # Very light cream container
            on_secondary_container="#553D00",# Dark brown text on secondary container

            background="#F8F2DE",            # Very light cream background
            on_background="#3A1B00",         # Dark brown text on background

            surface="#FFFFFF",               # White surface for cards etc.
            on_surface="#3A1B00",            # Dark brown text on surface

            error="#B00020",
            on_error="#FFFFFF",
        )
    )
    page.dark_theme = ft.Theme(
        color_scheme=ft.ColorScheme(
            primary="#D84040",               # Same primary vibrancy
            on_primary="#FFFFFF",            # Light text/icons on primary
            primary_container="#6E2C2C",    # Darker shade for container
            on_primary_container="#FBE8E8", # Light text on container

            secondary="#A31D1D",             # Same secondary
            on_secondary="#FFFFFF",          # Light text icons
            secondary_container="#4F0A0A",  # Darker container
            on_secondary_container="#FBE8E8",# Light text

            background="#121212",             # Deep dark background
            on_background="#FFFFFF",          # Light text

            surface="#121212",                # Same as background
            on_surface="#FFFFFF",

            error="#CF6679",
            on_error="#000000",
        )
    )

    router = Router(page, [ViewRoute(route, view_factory) for route, view_factory in ROUTE_MAP.items()])
    router.goto(Routes.HOME)


ft.app(main) # type: ignore
