name: flet_reactive
description: Flet FletReactive control
repository: https://github.com/MyGithubAccount/flet-reactive/src/flutter/flet_reactive
version: 1.0.0
homepage: https://github.com/MyGithubAccount/flet-reactive

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
