SCHEMA="""
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS LANGUAGES(ID INTEGER PRIMARY KEY, LANG NVARCHAR(16) NOT NULL COLLATE NOCASE, FALLBACK INTEGER);
CREATE TABLE IF NOT EXISTS STRINGS (STRING_ID INTEGER NOT NULL,LANG integer NOT NULL,VERSION integer NOT NULL,TEXT nvarchar(4000) COLLATE NOCASE,FOREIGN KEY (LANG) REFERENCES LANGUAGES(ID),FOREIGN KEY (STRING_ID) REFERENCES STRING_INFO(STRING_ID));
CREATE TABLE IF NOT EXISTS STRING_INFO ( STRING_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, RESOURCE NVARCHAR( 4000 ) NOT NULL COLLATE NOCASE, PROPERTY_NAME NVARCHAR( 4000 ) NOT NULL COLLATE NOCASE, VOICEOVER_NAME CHAR( 32 ) COLLATE NOCASE, STRING_KEY CHAR( 128 ) COLLATE NOCASE);
INSERT INTO "LANGUAGES" ("ID","LANG","FALLBACK") VALUES 
 (1,'PL',20),
 (2,'EN',1),
 (3,'DE',2),
 (4,'IT',2),
 (5,'FR',2),
 (6,'CZ',2),
 (7,'ES',2),
 (8,'ZH',2),
 (9,'RU',2),
 (10,'HU',2),
 (11,'JP',2),
 (12,'TR',2),
 (13,'KR',2),
 (14,'BR',2),
 (15,'ESMX',2),
 (16,'CN',2),
 (17,'AR',2),
 (20,'DEBUG',1);
CREATE VIEW FALLBACKS AS SELECT L1.ID AS ID, L2.ID AS FALLBACK_ID, L2.LANG AS FALLBACK_LANG FROM LANGUAGES AS L1 INNER JOIN LANGUAGES AS L2 ON L1.FALLBACK = L2.ID;
CREATE VIEW LATEST_STRINGS AS SELECT STR1.STRING_ID, STR1.LANG, STR1.VERSION, STR1.TEXT FROM STRINGS AS STR1 WHERE STR1.VERSION = (SELECT MAX(STR2.VERSION) FROM STRINGS AS STR2 WHERE STR2.STRING_ID = STR1.STRING_ID AND STR2.LANG = STR1.LANG);
CREATE VIEW LATEST_STRINGS_WITH_INFO_NEW AS SELECT INFO.STRING_ID, STR.LANG, STR.VERSION, STR.TEXT, INFO.STRING_ID AS Expr1, INFO.RESOURCE, INFO.PROPERTY_NAME, INFO.VOICEOVER_NAME, INFO.STRING_KEY FROM STRING_INFO AS INFO LEFT JOIN LATEST_STRINGS AS STR ON STR.STRING_ID = INFO.STRING_ID LEFT JOIN LANGUAGES AS LAN ON STR.LANG = LAN.ID;
CREATE VIEW STRINGS_VIEW AS SELECT STRING_ID, LANG, VERSION, TEXT FROM STRINGS;
CREATE INDEX STRINGS_FK_STRINGS_LANGUAGES ON STRINGS (LANG DESC);
CREATE UNIQUE INDEX STRINGS_PK_STRID_VERSION ON STRINGS (STRING_ID DESC, VERSION DESC);
CREATE INDEX STRING_INFO_STRING_KEY_IDX ON STRING_INFO (STRING_KEY DESC);
COMMIT;
"""
