from typing import Dict, Callable, Any, TypeVar, final, List

import flet as ft
from flet.core.text_style import StrutStyle

from flet_reactive.state import State
from flet_reactive.state_observer import StateObserver


_T = TypeVar('_T')

def _unwrap_value(v: _T | State[_T]) -> _T:
    if isinstance(v, State):
        return v.value
    else:
        return v

@final
class _StatefulPropertyBinding(StateObserver[_T]):
    def __init__(self, state: State[_T], ctrl: ft.Control, prop: str) -> None:
        self.state = state
        self.target_ctrl = ctrl
        self.target_prop = prop

        self.state.add_observer(self)

    def on_state_changed(self, old_state: _T, new_state: _T) -> None:
        setattr(self.target_ctrl, self.target_prop, new_state)
        self.target_ctrl.update()

    def sync_state(self) -> None:
        self.state.value = getattr(self.target_ctrl, self.target_prop)

    def drop(self):
        self.state.remove_observer(self)

class _ReactiveControlWrapper:
    def __init__(self) -> None:
        self.__prop_bindings = list[_StatefulPropertyBinding[Any]]()

    def _new_stateful_prop_binding(self, state: State[_T], target_ctrl: ft.Control, target_prop: str) -> _StatefulPropertyBinding:
        binding = _StatefulPropertyBinding(state, target_ctrl, target_prop)
        self.__prop_bindings.append(binding)
        return binding

    def _set_state(self, state: State[_T], value: _T):
        state.value = value

    def _drop_prop_bindings(self):
        for pso in self.__prop_bindings:
            pso.drop()


"""
Standard Flet controls supplied with reactive properties.
These get added as they're demanded.
"""

class ReactiveCheckbox(ft.Checkbox, _ReactiveControlWrapper):
    def __init__(self, 
        label: str | ft.Control | None = None, 
        value: bool | None | State[bool | None] = None, 
        label_position: ft.LabelPosition | None = None, 
        label_style: ft.TextStyle | None = None, 
        tristate: bool | None = None, 
        autofocus: bool | None = None, 
        fill_color: None | str | ft.Colors | ft.CupertinoColors | Dict[ft.ControlState, str | ft.Colors | ft.CupertinoColors] = None, 
        overlay_color: None | str | ft.Colors | ft.CupertinoColors | Dict[ft.ControlState, str | ft.Colors | ft.CupertinoColors] = None, 
        check_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        active_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        hover_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        focus_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        semantics_label: str | None = None, 
        shape: ft.OutlinedBorder | None = None, 
        splash_radius: int | float | None = None, 
        border_side: None | ft.BorderSide | Dict[ft.ControlState, ft.BorderSide] = None, 
        is_error: bool | None = None, visual_density: ft.VisualDensity | None = None, 
        mouse_cursor: ft.MouseCursor | None = None, 
        on_change: Callable[[ft.ControlEvent], Any] | None = None, 
        on_focus: Callable[[ft.ControlEvent], Any] | None = None, 
        on_blur: Callable[[ft.ControlEvent], Any] | None = None, 
        ref: ft.Ref | None = None, 
        key: str | None = None, 
        width: int | float | None = None, 
        height: int | float | None = None, 
        left: int | float | None = None, 
        top: int | float | None = None, 
        right: int | float | None = None, 
        bottom: int | float | None = None, 
        expand: None | bool | int = None, 
        expand_loose: bool | None = None, 
        col: Dict[str, int | float] | int | float | None = None, 
        opacity: int | float | None = None, 
        rotate: int | float | ft.Rotate | None = None, 
        scale: int | float | ft.Scale | None = None, 
        offset: ft.Offset | None = None, 
        aspect_ratio: int | float | None = None, 
        animate_opacity: bool | int | ft.Animation | None = None, 
        animate_size: bool | int | ft.Animation | None = None, 
        animate_position: bool | int | ft.Animation | None = None, 
        animate_rotation: bool | int | ft.Animation | None = None, 
        animate_scale: bool | int | ft.Animation | None = None, 
        animate_offset: bool | int | ft.Animation | None = None, 
        on_animation_end: Callable[[ft.ControlEvent], Any] | None = None, 
        tooltip: str | ft.Tooltip | None = None, 
        badge: str | ft.Badge | None = None, 
        visible: bool | None = None, 
        disabled: bool | None = None, 
        data: Any = None, 
        adaptive: bool | None = None
    ):
        super().__init__(
            label, 
            _unwrap_value(value), 
            label_position, 
            label_style, 
            tristate, 
            autofocus, 
            fill_color, 
            overlay_color, 
            check_color, 
            active_color, 
            hover_color, 
            focus_color, 
            semantics_label, 
            shape, 
            splash_radius, 
            border_side, 
            is_error, 
            visual_density, 
            mouse_cursor, 
            on_change, 
            on_focus, 
            on_blur, 
            ref, 
            key, 
            width, 
            height, 
            left, 
            top, 
            right, 
            bottom, 
            expand, 
            expand_loose, 
            col, 
            opacity, 
            rotate, 
            scale, 
            offset, 
            aspect_ratio, 
            animate_opacity, 
            animate_size, 
            animate_position, 
            animate_rotation, 
            animate_scale, 
            animate_offset, 
            on_animation_end, 
            tooltip, 
            badge, 
            visible, 
            disabled, 
            data, 
            adaptive
        )

        if isinstance(value, State):
            self.__state_value = value
            binding = self._new_stateful_prop_binding(self.__state_value, self, 'value')
            self._add_event_handler('change', lambda ev: binding.sync_state())

    def will_unmount(self):
        super().will_unmount()
        self._drop_prop_bindings()


class ReactiveTextField(ft.TextField, _ReactiveControlWrapper):
    def __init__(self, 
        value: str | None | State[str | None] = None, 
        keyboard_type: ft.KeyboardType | None = None, 
        multiline: bool | None = None, 
        min_lines: int | None = None, 
        max_lines: int | None = None, 
        max_length: int | None = None, 
        password: bool | None = None, 
        can_reveal_password: bool | None = None, 
        read_only: bool | None = None, 
        shift_enter: bool | None = None, 
        text_align: ft.TextAlign | None = None, 
        autofocus: bool | None = None, 
        capitalization: ft.TextCapitalization | None = None, 
        autocorrect: bool | None = None, 
        enable_suggestions: bool | None = None, 
        smart_dashes_type: bool | None = None, 
        smart_quotes_type: bool | None = None, 
        show_cursor: bool | None = None, 
        cursor_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        cursor_error_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        cursor_width: int | float | None = None, 
        cursor_height: int | float | None = None, 
        cursor_radius: int | float | None = None, 
        selection_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        input_filter: ft.InputFilter | None = None, 
        obscuring_character: str | None = None, 
        enable_interactive_selection: bool | None = None, 
        enable_ime_personalized_learning: bool | None = None, 
        can_request_focus: bool | None = None, 
        ignore_pointers: bool | None = None, 
        enable_scribble: bool | None = None, 
        animate_cursor_opacity: bool | None = None, 
        always_call_on_tap: bool | None = None, 
        scroll_padding: int | float | ft.Padding | None = None, 
        clip_behavior: ft.ClipBehavior | None = None, 
        keyboard_brightness: ft.Brightness | None = None, 
        mouse_cursor: ft.MouseCursor | None = None, 
        strut_style: StrutStyle | None = None, 
        autofill_hints: None | ft.AutofillHint | List[ft.AutofillHint] = None, 
        on_change: Callable[[ft.ControlEvent], Any] | None = None, 
        on_click: Callable[[ft.ControlEvent], Any] | None = None, 
        on_submit: Callable[[ft.ControlEvent], Any] | None = None, 
        on_focus: Callable[[ft.ControlEvent], Any] | None = None, 
        on_blur: Callable[[ft.ControlEvent], Any] | None = None, 
        on_tap_outside: Callable[[ft.ControlEvent], Any] | None = None, 
        text_size: int | float | None = None, 
        text_style: ft.TextStyle | None = None, 
        text_vertical_align: ft.VerticalAlignment | int | float | None = None, 
        label: str | ft.Control | None = None, 
        label_style: ft.TextStyle | None = None, 
        icon: str | ft.Icons | ft.CupertinoIcons | Any | None = None, 
        border: ft.InputBorder | None = None, 
        color: str | ft.Colors | ft.CupertinoColors | None = None, 
        bgcolor: str | ft.Colors | ft.CupertinoColors | None = None, 
        border_radius: int | float | ft.BorderRadius | None = None, 
        border_width: int | float | None = None, 
        border_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        focused_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        focused_bgcolor: str | ft.Colors | ft.CupertinoColors | None = None, 
        focused_border_width: int | float | None = None, 
        focused_border_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        content_padding: int | float | ft.Padding | None = None, 
        dense: bool | None = None, 
        filled: bool | None = None, 
        fill_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        hover_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        hint_text: str | None = None, 
        hint_style: ft.TextStyle | None = None, 
        helper: ft.Control | None = None, 
        helper_text: str | None = None, 
        helper_style: ft.TextStyle | None = None, 
        counter: ft.Control | None = None, 
        counter_text: str | None = None, 
        counter_style: ft.TextStyle | None = None, 
        error: ft.Control | None = None, 
        error_text: str | None = None, 
        error_style: ft.TextStyle | None = None, 
        prefix: ft.Control | None = None, 
        prefix_icon: str | ft.Icons | ft.CupertinoIcons | Any | None = None, 
        prefix_text: str | None = None, 
        prefix_style: ft.TextStyle | None = None, 
        suffix: ft.Control | None = None, 
        suffix_icon: str | ft.Icons | ft.CupertinoIcons | Any | None = None, 
        suffix_text: str | None = None, 
        suffix_style: ft.TextStyle | None = None, 
        focus_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        align_label_with_hint: bool | None = None, 
        hint_fade_duration: int | ft.Duration | None = None, 
        hint_max_lines: int | None = None, 
        helper_max_lines: int | None = None, 
        error_max_lines: int | None = None, 
        prefix_icon_size_constraints: ft.BoxConstraints | None = None, 
        suffix_icon_size_constraints: ft.BoxConstraints | None = None, 
        size_constraints: ft.BoxConstraints | None = None, 
        collapsed: bool | None = None, 
        fit_parent_size: bool | None = None, 
        ref: ft.Ref | None = None, 
        key: str | None = None, 
        width: int | float | None = None, 
        height: int | float | None = None, 
        expand: None | bool | int = None, 
        expand_loose: bool | None = None, 
        col: Dict[str, int | float] | int | float | None = None, 
        opacity: int | float | None = None, 
        rotate: int | float | ft.Rotate | None = None, 
        scale: int | float | ft.Scale | None = None, 
        offset: ft.Offset | None = None, 
        aspect_ratio: int | float | None = None, 
        animate_opacity: bool | int | ft.Animation | None = None, 
        animate_size: bool | int | ft.Animation | None = None, 
        animate_position: bool | int | ft.Animation | None = None, 
        animate_rotation: bool | int | ft.Animation | None = None, 
        animate_scale: bool | int | ft.Animation | None = None, 
        animate_offset: bool | int | ft.Animation | None = None, 
        on_animation_end: Callable[[ft.ControlEvent], Any] | None = None, 
        tooltip: str | ft.Tooltip | None = None, 
        badge: str | ft.Badge | None = None, 
        visible: bool | None = None, 
        disabled: bool | None = None, 
        data: Any = None, 
        rtl: bool | None = None, 
        adaptive: bool | None = None
    ):
        super().__init__(
            _unwrap_value(value),
            keyboard_type,
            multiline,
            min_lines,
            max_lines,
            max_length,
            password,
            can_reveal_password,
            read_only,
            shift_enter,
            text_align,
            autofocus,
            capitalization,
            autocorrect,
            enable_suggestions,
            smart_dashes_type,
            smart_quotes_type,
            show_cursor,
            cursor_color,
            cursor_error_color,
            cursor_width,
            cursor_height,
            cursor_radius,
            selection_color,
            input_filter,
            obscuring_character,
            enable_interactive_selection,
            enable_ime_personalized_learning,
            can_request_focus,
            ignore_pointers,
            enable_scribble,
            animate_cursor_opacity,
            always_call_on_tap,
            scroll_padding,
            clip_behavior,
            keyboard_brightness,
            mouse_cursor,
            strut_style,
            autofill_hints,
            on_change,
            on_click,
            on_submit,
            on_focus,
            on_blur,
            on_tap_outside,
            text_size,
            text_style,
            text_vertical_align,
            label,
            label_style,
            icon,
            border,
            color,
            bgcolor,
            border_radius,
            border_width,
            border_color,
            focused_color,
            focused_bgcolor,
            focused_border_width,
            focused_border_color,
            content_padding,
            dense,
            filled,
            fill_color,
            hover_color,
            hint_text,
            hint_style,
            helper,
            helper_text,
            helper_style,
            counter,
            counter_text,
            counter_style,
            error,
            error_text,
            error_style,
            prefix,
            prefix_icon,
            prefix_text,
            prefix_style,
            suffix,
            suffix_icon,
            suffix_text,
            suffix_style,
            focus_color,
            align_label_with_hint,
            hint_fade_duration,
            hint_max_lines,
            helper_max_lines,
            error_max_lines,
            prefix_icon_size_constraints,
            suffix_icon_size_constraints,
            size_constraints,
            collapsed,
            fit_parent_size,
            ref,
            key,
            width,
            height,
            expand,
            expand_loose,
            col,
            opacity,
            rotate,
            scale,
            offset,
            aspect_ratio,
            animate_opacity,
            animate_size,
            animate_position,
            animate_rotation,
            animate_scale,
            animate_offset,
            on_animation_end,
            tooltip,
            badge,
            visible,
            disabled,
            data,
            rtl,
            adaptive
        )

        if isinstance(value, State):
            self.__state_value = value
            binding = self._new_stateful_prop_binding(self.__state_value, self, 'value')
            self._add_event_handler('change', lambda ev: binding.sync_state())

    def will_unmount(self):
        super().will_unmount()
        self._drop_prop_bindings()


class ReactiveFilledButton(ft.FilledButton, _ReactiveControlWrapper):
    def __init__(self, 
        text: str | None = None, 
        icon: str | ft.Icons | ft.CupertinoIcons | None = None, 
        icon_color: str | ft.Colors | ft.CupertinoColors | None = None, 
        color: str | ft.Colors | ft.CupertinoColors | None = None, 
        bgcolor: str | ft.Colors | ft.CupertinoColors | None = None, 
        content: ft.Control | None = None, 
        elevation: int | float | None = None, 
        style: ft.ButtonStyle | None = None, 
        autofocus: bool | None = None, 
        clip_behavior: ft.ClipBehavior | None = None, 
        url: str | None = None, 
        url_target: ft.UrlTarget | None = None, 
        on_click: Callable[[ft.ControlEvent], Any] | None = None, 
        on_long_press: Callable[[ft.ControlEvent], Any] | None = None, 
        on_hover: Callable[[ft.ControlEvent], Any] | None = None, 
        on_focus: Callable[[ft.ControlEvent], Any] | None = None, 
        on_blur: Callable[[ft.ControlEvent], Any] | None = None, 
        ref: ft.Ref | None = None, 
        key: str | None = None, 
        width: int | float | None = None, 
        height: int | float | None = None, 
        left: int | float | None = None, 
        top: int | float | None = None, 
        right: int | float | None = None, 
        bottom: int | float | None = None, 
        expand: None | bool | int = None, 
        expand_loose: bool | None = None, 
        col: Dict[str, int | float] | int | float | None = None, 
        opacity: int | float | None = None, 
        rotate: int | float | ft.Rotate | None = None, 
        scale: int | float | ft.Scale | None = None, 
        offset: ft.Offset | None = None, 
        aspect_ratio: int | float | None = None, 
        animate_opacity: bool | int | ft.Animation | None = None, 
        animate_size: bool | int | ft.Animation | None = None, 
        animate_position: bool | int | ft.Animation | None = None, 
        animate_rotation: bool | int | ft.Animation | None = None, 
        animate_scale: bool | int | ft.Animation | None = None, 
        animate_offset: bool | int | ft.Animation | None = None, 
        on_animation_end: Callable[[ft.ControlEvent], Any] | None = None, 
        tooltip: str | ft.Tooltip | None = None, 
        badge: str | ft.Badge | None = None, 
        visible: bool | None = None, 
        disabled: bool | None | State[bool | None] = None, 
        data: Any = None, 
        adaptive: bool | None = None
    ):
        super().__init__(
            text, 
            icon, 
            icon_color, 
            color, 
            bgcolor, 
            content, 
            elevation, 
            style, 
            autofocus, 
            clip_behavior, 
            url, 
            url_target, 
            on_click, 
            on_long_press, 
            on_hover, 
            on_focus, 
            on_blur, 
            ref, 
            key, 
            width, 
            height, 
            left, 
            top, 
            right, 
            bottom, 
            expand, 
            expand_loose, 
            col, 
            opacity, 
            rotate, 
            scale, 
            offset, 
            aspect_ratio, 
            animate_opacity, 
            animate_size, 
            animate_position, 
            animate_rotation, 
            animate_scale, 
            animate_offset, 
            on_animation_end, 
            tooltip, 
            badge, 
            visible, 
            _unwrap_value(disabled), 
            data, 
            adaptive
        )

        if isinstance(disabled, State):
            self.__state_disabled = disabled
            binding = self._new_stateful_prop_binding(self.__state_disabled, self, 'disabled')

    def will_unmount(self):
        super().will_unmount()
        self._drop_prop_bindings()