name: draft-release

on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Produce .pyz
      run:
        python tasks/zip_cli.py
    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "out/w3stringsx.pyz"
        draft: true
        generateReleaseNotes: true